CREATE TABLE USER (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_FNAME VARCHAR(50),
    USER_LNAME VARCHAR(50),
    USER_EMAIL VARCHAR(100),
    USER_PASSWORD VARCHAR(256),
    USER_TYPE ENUM('STUDENT', 'TUTOR', 'ADMIN'),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE STUDENT (
    STUDENT_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT,
    STUDENT_GRADE INT,
    STUDENT_MAJOR VARCHAR(50),
    STUDENT_GPA DECIMAL(3,2),
    PRIMARY KEY (STUDENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE TUTOR (
    TUTOR_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT,
    TUTOR_AVAIL VARCHAR(200),
    TUTOR_SUBJECTS VARCHAR(200),
    PRIMARY KEY (TUTOR_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE ADMIN (
    ADMIN_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT,
    ADMIN_INFO VARCHAR(200),
    PRIMARY KEY (ADMIN_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);
CREATE TABLE currentUser (
  current_id INT NOT NULL,
  PRIMARY KEY (current_id)
);

CREATE TABLE FILE_CONSTANTS (
    FILE_ID INT NOT NULL AUTO_INCREMENT,
    FILE_EXTENSION VARCHAR(10) NOT NULL,
    FILE_SIZE INT NOT NULL,
    PRIMARY KEY (FILE_ID)
);

CREATE TABLE USER_FILE_PROPERTIES (
    FILE_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_UPLOAD_DATE DATETIME NOT NULL,
    PRIMARY KEY (FILE_ID, USER_ID),
    FOREIGN KEY (FILE_ID) REFERENCES FILE_CONSTANTS(FILE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);


